name: feather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  html: ^0.15.4
  intl: ^0.19.0
  logger: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
